### ISSUE TITLE
QA_NC_Documents

### ISSUE THREAD

**Issue by kolliSuman** [vlead/outreach-portal#110]
Defect Description:
In the Workshop Documents page of Documents,the view option is missing instead the 'view' option should be placed inorder to view a particular document by the NC.

Actual Result:
In the Workshop Documents page of Documents,the view option is missing.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5,

Test Step Link:
https://github.com/vlead/outreach-portal/blob/master/test-cases/integration_test-cases/NC/NC_46_Documents_smk.org

Attachments : 
![doc view](https://cloud.githubusercontent.com/assets/14869397/12215370/e2b9b8f0-b6df-11e5-95a1-1381aa451f9c.png)

**Comment by varshanihanth** [comment]
as it didn't change from click here to view we are reopening this defect

**Comment by varshanihanth** [comment]
as it didn't change from click here to view we are reopening this defect

**Comment by varshanihanth** [comment]
Now it is reflecting

**Comment by varshanihanth** [comment]
Replace the header download to "Action"

**Comment by dinnu93** [comment]
Removed headings for all the buttons because button actions are self explanatory.
