### ISSUE TITLE
QA_DM_DOC

### ISSUE THREAD

**Issue by varshanihanth** [vlead/outreach-portal#138]
Users : R.K. Katiyar
Defect Description:
The list of documents are mismatching from the old portal to the new portal

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5,

![docn](https://cloud.githubusercontent.com/assets/14229099/12260046/826284e8-b93f-11e5-8bc1-7a22508e9f41.png)
![doc o](https://cloud.githubusercontent.com/assets/14229099/12260047/82790e84-b93f-11e5-97ed-41bbd3740ad8.png)

**Comment by varshanihanth** [comment]
QA team reopens this defect, as college report file is not displaying in the new portal where it is present in the old portal,

**Comment by dinnu93** [comment]
In the new portal NC can view the documents uploaded by Admin.In the above case, college report file is not present in Admin documents. Hence not displaying.

**Comment by dinnu93** [comment]
In the old outreach portal file paths are hard coded.

**Comment by varshanihanth** [comment]
considering the @dinnu93 comment, the QA team is closing this issue
