### ISSUE TITLE
QA_NC_Manage Workshops

### ISSUE THREAD

**Issue by varshanihanth** [vlead/outreach-portal#143]
Defect Description: When we delete the workshop, a pop-up box is displayed to enter the reason, where does this reason stores and where are the deleted workshops displayed in the portal? Even if we don't enter the reason and if we click on the cancel button the workshop is getting deleted where it shouldn't 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5,

![sc](https://cloud.githubusercontent.com/assets/14229099/12285252/2e2a0654-b9de-11e5-96af-1b6377b9084b.png)

**Comment by dinnu93** [comment]
Saving cancelled workshops and the reason are for future reference and not listed anywhere in the scenario.
