### ISSUE TITLE
QA_Admin_Manage Documents

### ISSUE THREAD

**Issue by varshanihanth** [vlead/outreach-portal#144]
Defect Description:In the documents page the headers field are placed as view and delete instead they should be replaced with "Action" 

An unique format should be maintained through out the portal

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5,

![vd](https://cloud.githubusercontent.com/assets/14229099/12414158/a32f0046-beb9-11e5-9237-72bb7aa75513.png)

**Comment by dinnu93** [comment]
Removed headings for all the buttons because button actions are self explanatory.
