### ISSUE TITLE
QA_OC_Upload Reports

### ISSUE THREAD

**Issue by varshanihanth** [vlead/outreach-portal#146]
Defect Description:In the upload reports page, it should accept/allow to upload single file also

Description: When we upload a report in photos and if we click on the upload button an error message is displaying on the screen as to upload files in attendance sheets and college reports also

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5,

![upload](https://cloud.githubusercontent.com/assets/14229099/12440312/2e4c09ac-bf60-11e5-8b0d-c0e3e7e54aaf.png)

**Comment by varshanihanth** [comment]
In the upload reports page, when we try to upload multiple files by using the ctrl key it is not accepting where it should allow th upload

**Comment by dinnu93** [comment]
The above screen shot is of NC for which the issue is fixed

**Comment by dinnu93** [comment]
Multiple file uploads are working.
