### ISSUE TITLE
QA_OC_Upload Reports

### ISSUE THREAD

**Issue by varshanihanth** [vlead/outreach-portal#147]
Defect Description:In review reports page the headers field are placed as delete instead it should be replaced with "Action"

An unique format should be maintained through out the portal

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5,

![header](https://cloud.githubusercontent.com/assets/14229099/12441446/3bdd3f02-bf6d-11e5-8881-4987b6dd3777.png)

**Comment by kolliSuman** [comment]
header field is removed for all the buttons in the portal
