### ISSUE TITLE
OC_Manage workshop_Delete

### ISSUE THREAD

**Issue by kolliSuman** [vlead/outreach-portal#159]
Defect Description:
In workshop history of manage workshop,when we click on upload reports,delete button  options for Attendance and Reports is not working instead OC should be able delete Attendance and Reports

Actual Result:
In workshop history of manage workshop,when we click on upload reports,delete button  options for Attendance and Reports is not working

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5
![screenshot 13](https://cloud.githubusercontent.com/assets/14869397/13878885/4c6819b4-ed3a-11e5-9326-589af0a07d29.png)
![screenshot 14](https://cloud.githubusercontent.com/assets/14869397/13878897/5c6e4f90-ed3a-11e5-82d0-d44d519a9e6c.png)

**Comment by dinnu93** [comment]
Hi Suman, I tested this bug and tried to delete the report and it deleted the report. I'm attaching a screenshot.
![screenshot from 2016-03-19 11-32-55](https://cloud.githubusercontent.com/assets/3586932/13896985/b077bf90-edc6-11e5-86f5-8e8f0f76ff1c.png)
![screenshot from 2016-03-19 11-33-18](https://cloud.githubusercontent.com/assets/3586932/13896984/b073b26a-edc6-11e5-86b1-0dce382c8014.png)

**Comment by kolliSuman** [comment]
after clicking on the delete button if we click on the view the bellow error message is displaying .

{
  "error": "The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again."
}

**Comment by dinnu93** [comment]
It's an extremely rare bug which happens only when Internet goes off on server and the file deletion request is half processed i.e file is deleted in the respective folder but the database path is not. I couldn't replicate the bug so I rejected it.
