### ISSUE TITLE
Use full names and consistent terminology

### ISSUE THREAD

**Issue by vxc** [vlead/outreach-portal#161]
Is NC nodal center   or Nodal Coordinator?

I suggest that we  have standard terminology

OC: Outreach Center
NC: Nodal Center
NCC: Nodal Center Coordinator
OCC: Outreach Center Coordinator
IOC: Institute outreach coordinator (alias for OCC)

Please do not abbreviations in the displays, use full names.

**Comment by dinnu93** [comment]
For now included relevant abbreviations which will help differentiate between things like a Nodal Coordinator and a Nodal Centre. We've taken the suggestions into consideration and will be included uniformly in next release.
