### ISSUE TITLE
Backup script has to be modified

### ISSUE THREAD

**Issue by ksripathi** [vlead/outreach-portal#175]

**Comment by ksripathi** [comment]
Currently outreach portal's backup tar file is created using below command. This command will append files to the end of an archive. This will leads to heavy size of the file.
tar --append --file=$OUT_FILE $DOC_FOLDER $DB_NAME.sql
We should remove --append argument from above command.

**Comment by ksripathi** [comment]
Removed above argument --append and replace with -cvf argument.
tar -cvf $OUT_FILE $DOC_FOLDER $DB_NAME.sql

This issue is resolved directly on production source code needs to be updated on develop branch

**Comment by madhavipuliraju** [comment]
Backup and Restore scripts are modified to take only the Mysql Database backup.

**Comment by madhavipuliraju** [comment]
Backup and Restore scripts are modified to take only the Mysql Database backup.
