### ISSUE TITLE
Expose Google Maps API key to only *.vlabs.ac.in (or) *.virtual-labs.ac.in origins

### ISSUE THREAD

**Issue by ksripathi** [vlead/outreach-portal#209]
Currently in Outreach Portal Google Maps API key is unrestricted. To prevent unauthorized use and quota theft and to restrict the key Google allowed us to specify for which web sites, IP addresses, or apps can use this key.

**Comment by ksripathi** [comment]
This is resolved by adding following domains into the allowed website in google settings.

1)  *.vlabs.ac.in
2) *.virtual-labs.ac.in

**Comment by travula** [comment]
Captured y the [design](https://github.com/vlead/outreach-portal/blob/develop/src/design.org#map-locators).
