### ISSUE TITLE
redirect al ltraffic on http (port 80) to https (443)

### ISSUE THREAD

**Issue by travula** [vlead/outreach-portal#211]
http://stackoverflow.com/questions/4083221/how-to-redirect-all-http-requests-to-https/21798882#21798882

**Comment by ksripathi** [comment]
Outreach Portal always redirects to http://outreach.virtual-labs.ac.in domain. Since there are no certificates installed for virtual-labs.ac.in domain. https protocol won't work.

Once the System team updates the certificates for virtual-labs domain this issue will be resolved.
