### ISSUE TITLE
Processing images (.gif) to be added to all anlytics blocks

### ISSUE THREAD

**Issue by ksripathi** [vlead/outreach-portal#213]
Since all numbers on dashbords and anlytics band on landing page are calculated by making http request to APIs. Since it is an http request there will be latency issue to get the numbers from response. It is good to have processing images (.gif) for such block before the actual numbers are calculated from APIs. So that user will know that there is a latency issue.

**Comment by madhavipuliraju** [comment]
Implemented materialized views for the analytics on landing page. This views will load within no time. Now, there is no latency issue. Hence, removed Processing images (.gif).
