### ISSUE TITLE
Workshop Details to be made public

### ISSUE THREAD

**Issue by priya100raman** [vlead/outreach-portal#229]
Click on the Workshop tab on the outreach portal to list all the approved workshops : Name, College/Institute Name, Date of the Workshop , Reports , Nodal Coordinator ( Please add any other details as deemed necessary)

**Comment by ksripathi** [comment]
All approved workshops are made publicly accessible

**Comment by ksripathi** [comment]
Beautification of the web pages are yet to be worked on
