### ISSUE TITLE
QA_OC_Manage NodalCentres

### ISSUE THREAD

**Issue by kolliSuman** [vlead/outreach-portal#23]
Defect Description:
In the Manage Nodal Centres page, if there is only one nodal centre created and if we click on the delete button corresponding to it , the nodal centre is not getting deleted instead the nodal centre should get deleted.

Actual Result:
In the Manage Nodal Centres page, if there is only one nodal centre created and if we click on the delete button corresponding to it , the nodal centre is not getting deleted.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Test Step Link:
https://github.com/vlead/outreach-portal/blob/master/test-cases/integration_test-cases/OC/OC_88_Manage%20Nodal-Centre_p1.org

Attachment : 
![3](https://cloud.githubusercontent.com/assets/14869397/12034015/f2ec661a-ae50-11e5-8f91-53442d0e44d5.png)

**Comment by ksripathi** [comment]
Hello Suman,

First you should delete the nodal coordinator which is associated with nodal center then only you can delete nodal center anyway in this case i can display a alert message.
