### ISSUE TITLE
Snapshot of issues captured by CDAC

### ISSUE THREAD

**Issue by ksripathi** [vlead/outreach-portal#251]
issue : [#12](https://gitlab.com/vlead-systems/vlead-security-audit/issues/12) , commit id :
issue :[#13](https://gitlab.com/vlead-systems/vlead-security-audit/issues/13), commit id :
issue :[#14](https://gitlab.com/vlead-systems/vlead-security-audit/issues/14), commit id :
issue :[#15](https://gitlab.com/vlead-systems/vlead-security-audit/issues/15), commit id :
issue :[#16](https://gitlab.com/vlead-systems/vlead-security-audit/issues/12), commit id :
issue :[#17](https://gitlab.com/vlead-systems/vlead-security-audit/issues/17), commit id :
issue :[#18](https://gitlab.com/vlead-systems/vlead-security-audit/issues/18), commit id :
issue :[#19](https://gitlab.com/vlead-systems/vlead-security-audit/issues/19), commit id :
issue :[#20](https://gitlab.com/vlead-systems/vlead-security-audit/issues/20), commit id :
issue :[#60](https://gitlab.com/vlead-systems/vlead-security-audit/issues/60), commit id :
issue :[#61](https://gitlab.com/vlead-systems/vlead-security-audit/issues/61), commit id :
issue :[#62](https://gitlab.com/vlead-systems/vlead-security-audit/issues/62), commit id :
issue :[#63](https://gitlab.com/vlead-systems/vlead-security-audit/issues/63), commit id :

**Comment by madhavipuliraju** [comment]
All this issues are resolved. Please find the status of each issue on gitlab.
