### ISSUE TITLE
Integrate footer service

### ISSUE THREAD

**Issue by travula** [vlead/outreach-portal#260]
Currently, the footer service is not used.  Please use this.

**Comment by madhavipuliraju** [comment]
Footer service is Down/Stopped. Hence for now Footer is updated with static links.

**Comment by madhavipuliraju** [comment]
![screenshot from 2019-02-25 13-00-37](https://user-images.githubusercontent.com/7077897/53321040-5e362980-38fd-11e9-8e33-d3cf53c3bb28.png)
