### ISSUE TITLE
Ensure all workshop reports are uploaded

### ISSUE THREAD

**Issue by ksripathi** [vlead/outreach-portal#261]
Currently in Outreach Portal, while uploading workshop reports it is made as not mandatory to upload all three sections attendance, photos and college report files. This should be made as mandatory

**Comment by madhavipuliraju** [comment]
![screenshot from 2019-02-25 13-02-08](https://user-images.githubusercontent.com/7077897/53321128-950c3f80-38fd-11e9-865e-282fbdb34371.png)
