### ISSUE TITLE
Google Oauth authentication is broken after security fixes

### ISSUE THREAD

**Issue by ksripathi** [vlead/outreach-portal#264]
After resolving issues https://gitlab.com/vlead-systems/vlead-security-audit/issues?scope=all&utf8=%E2%9C%93&state=opened&label_name[]=outreach raised by CDAC team. Google oauth authentication is broken. This is to be fixed

**Comment by madhavipuliraju** [comment]
Fixed.
commit id: [203cd5a4e4650c33e403ee9df5d35168e7fef8c4](https://github.com/vlead/outreach-portal/commit/203cd5a4e4650c33e403ee9df5d35168e7fef8c4)
