### ISSUE TITLE
New requirement : Sorting feature in workshop history details

### ISSUE THREAD

**Issue by mrudhvika940** [vlead/outreach-portal#266]
Sorting feature in workshop history details based on 
- Alphabetic A-Z / Z-A
- Date
- Highest/Lowest usage number
- Location

**Comment by madhavipuliraju** [comment]
The above requirement was redefined as follows: 
- 'Workshops' has to be sorted based on the 'Date' parameter
- 'Usage' has to be sorted based on 'Highest/Lowest usage number'
- 'Nodal Center's has to be sorted based on 'Alphabetic order A-Z/Z-A'

**Comment by madhavipuliraju** [comment]
Fixed.
Branch
https://github.com/vlead/outreach-portal/tree/sorting
