### ISSUE TITLE
Fix Google authentication on staging (base4) environments

### ISSUE THREAD

**Issue by ksripathi** [vlead/outreach-portal#271]
When Outreach Portal is integrated with Google Oauth on base4 server. After network call to Google API it throws following error for some network related reasons this is to be fixed

> Error in Google Authentication : Invalid response from Google

Whereas ADS service which runs on base4 server is also using Google Oauth which works as with no issues one can refer this https://github.com/vlead/ovpl/tree/master/src/ads-web-app and resolve the issue

**Comment by madhavipuliraju** [comment]
Fixed.
Commit Id: [203cd5a4e4650c33e403ee9df5d35168e7fef8c4](https://github.com/vlead/outreach-portal/commit/203cd5a4e4650c33e403ee9df5d35168e7fef8c4)
