### ISSUE TITLE
View for exporting the Workshop, Nodal Centers and Usage data

### ISSUE THREAD

**Issue by sanchita-dixit** [vlead/outreach-portal#275]
There should be a provision for exporting/downloading the data in CSV/PDF format from the Nodal Centers, Workshops Run and Usage fields from the main page of Outreach portal.

**Comment by madhavipuliraju** [comment]
ngCsv module is not working with the current implementation. Need to fix it.

**Comment by madhavipuliraju** [comment]
Fixed.
