### ISSUE TITLE
Segregation of Online and Offline workshops conducted

### ISSUE THREAD

**Issue by sanchita-dixit** [vlead/outreach-portal#276]
Currently there is no provision to separate the data for the offline and online workshops conducted. We need a feature for it. We should be able to filter all the workshops based on Online and Offline mode while NCs enter the data for the every new workshop they conduct.

**Comment by sadhanareddy** [comment]
@sanchita-dixit 
Need clarity on the mentioned requirement
1. This needs to be implemented with "login" or "without login" ? 
2. How the workshops data should be filtered with dropdown box or radio buttons ?

**Comment by madhavipuliraju** [comment]
commit ID: https://github.com/vlead/outreach-portal/commit/586b814dafcb1779dea5e840531dc5eb2d15bb8e
branch: https://github.com/vlead/outreach-portal/tree/filtering
