### ISSUE TITLE
New Requirement : The Outreach Portal home page should load within 2-3 seconds

### ISSUE THREAD

**Issue by sanchita-dixit** [vlead/outreach-portal#294]
Currently the outreach home page loading takes more time than expected which is hampering the User experience in terms of performance. The home page must load within 2-3 seconds on a 2G connection for a better experience.

**Comment by madhavipuliraju** [comment]
Reference: https://www.fromdual.com/mysql-materialized-views

**Comment by madhavipuliraju** [comment]
create `analytics` table to capture the numbers displayed on analytics band as shown in below table.

name | totalvalue
-- | --
WORKSHOPS RUN | 2980
UPCOMING WORKSHOPS | 3
NODAL CENTRES | 570
PARTICIPANTS ATTENDED | 554173
USAGE | 2704013

**Comment by madhavipuliraju** [comment]
Create a **on demand Materialized View** to capture the values mentioned in the above table.
A **Materialized View (MV)** is the pre-calculated (materialized) result of a query.
**on demand** (for example once a day, for example after nightly load)

**Comment by madhavipuliraju** [comment]
Implemented script to populate analytics table. 
commit Id: https://github.com/vlead/outreach-portal/commit/27e272c4cd4b90625f03b3336eca29df2ee86fe1

**Comment by madhavipuliraju** [comment]
Implemented Front end and Back end for analytics.
Commit Id: https://github.com/vlead/outreach-portal/pull/325/commits/4fb966e6e433b0e4fbb955e92f801659edb61bfe

**Comment by madhavipuliraju** [comment]
![screenshot from 2018-11-12 15-10-02](https://user-images.githubusercontent.com/7077897/48341410-f97afa00-e692-11e8-953c-f9f3c4af1035.png)
