### ISSUE TITLE
Grid view in outreach portal

### ISSUE THREAD

**Issue by mrudhvika940** [vlead/outreach-portal#297]
Currently there is no provision to seperate/sort/filter/ export the data in Nodal centers, workshops run, etc.,. We need a feature for it. The requirement is to build a Grid view with the features like filtering, sorting, exporting, pagination etc.,

**Comment by madhavipuliraju** [comment]
![Screenshot from 2019-04-30 09-57-45](https://user-images.githubusercontent.com/7077897/56940835-6cd3d380-6b2e-11e9-97ea-65e342109289.png)
