### ISSUE TITLE
QA_enhancements_tooltip_ui

### ISSUE THREAD

**Issue by BSravanthi** [vlead/outreach-portal#317]
Defect Description:
In the "add workshop" page of the outreach portal, we have found that the size of the text fields is changing. To these fields, the tooltip is activated, Whereas the size of the text field needs to be fixed. 

Actual Result:
When the mouse hovers on the text fields of "Workshop name", "Location of the workshop", "Workshop collage name" and "No of expected participants" the size of these text fields is changed. When the cursor is removed, the text field is returning to the previous size.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:

![qa_tooltip](https://user-images.githubusercontent.com/13479177/47717165-077c5400-dc6b-11e8-87c1-482ebd9cf14f.png)

**Comment by BalammaBoya** [comment]
Fixed the issue, the size of the text fields is changing when tooltip is activated. 

![screenshot from 2018-11-05 17-38-48](https://user-images.githubusercontent.com/22425444/47997312-633e5580-e121-11e8-96a8-6f4213a570fc.png)
