### ISSUE TITLE
QA_enhancements_tooltip_ui

### ISSUE THREAD

**Issue by BSravanthi** [vlead/outreach-portal#318]
Defect Description:
In the "add workshop" page of the outreach portal, we have found that the size of all text fields is not the same. The fields that are enhanced with tooltip are looking slight big comparatively to the fields before enhancement. 

Actual Result:
In the "add workshop" page of the outreach portal, we have found that the size of all text fields is not the same. The fields that are enhanced with tooltip are looking slight big comparatively to the fields before enhancement. 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:

**Comment by BalammaBoya** [comment]
Fixed the size of all text fields equally. 

![screenshot from 2018-11-05 17-38-41](https://user-images.githubusercontent.com/22425444/47997529-2de63780-e122-11e8-883a-f2a2f8bf0259.png)
