### ISSUE TITLE
Add active and inactive flags for Nodal Centre 

### ISSUE THREAD

**Issue by BalammaBoya** [vlead/outreach-portal#321]
A new attribute to be added with drop down (in the UI) to display the active/inactive status of IOC's and NC's. 
Changes should be incorporated in the database and user interface.

**Comment by madhavipuliraju** [comment]
![screenshot from 2019-02-25 12-47-42](https://user-images.githubusercontent.com/7077897/53320391-90df2280-38fb-11e9-9af7-1af316bc8985.png)
