### ISSUE TITLE
QA_enhancements_tooltip_functionality

### ISSUE THREAD

**Issue by BSravanthi** [vlead/outreach-portal#323]
Defect Description:
In the "add workshop" page of the outreach portal, found a discrepancy in the functionality of the error message. When a necessary field left unfilled and move to next field to fill an error message to appear.

Actual Result:
In the "add workshop" page of the outreach portal, found a discrepancy in the functionality of the error message. When a necessary field left unfilled and move to next field to fill, an error message to appear. In this enhancement found this discrepancy with 1st and 2nd text input fields. When these both fields left unfilled and move to next fields no error message is displayed. Whereas, no discrepancy with other fields when filled, erased and then move to other fields an error message is popping up.    

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:

**Comment by madhavipuliraju** [comment]
![screenshot from 2018-11-05 12-24-57](https://user-images.githubusercontent.com/7077897/47982651-87d10800-e0f6-11e8-9927-de74d04180a0.png)

**Comment by madhavipuliraju** [comment]
![screenshot from 2018-11-05 12-31-46](https://user-images.githubusercontent.com/7077897/47982724-c8c91c80-e0f6-11e8-9bc1-f04354c567b8.png)

In the above screenshot, submit button was not enabled if all mandatory fields are not given. Also, error messages were shown.
