### ISSUE TITLE
Remove gif, doc and docx file formats as they prone to security threat.

### ISSUE THREAD

**Issue by madhavipuliraju** [vlead/outreach-portal#329]
Remove gif, doc and docx file formats. Also, convert the existing files and related links also from doc, docx and gif to pdf.

**Comment by madhavipuliraju** [comment]
Fixed.
https://github.com/vlead/outreach-portal/commit/96bdb5ec52858d1729d96690af3b8edbfc6863e0

**Comment by madhavipuliraju** [comment]
Need to convert existing files from doc and docx to pdf format.

**Comment by madhavipuliraju** [comment]
Install LibreOffice and use the following commands to convert files from doc and docx to pdf.
```
lowriter --headless --convert-to pdf *.doc 
lowriter --headless --convert-to pdf *.docx 
rm -rf *.doc
rm -rf *.docx

```

**Comment by madhavipuliraju** [comment]
Also Update the db path in database using following commands.
```
update workshop_reports set path='%.pdf' where path like '%.doc';
update workshop_reports set path='%.pdf' where path like'%.docx';
update reference_documents set path='%.pdf' where path like '%.doc';
update reference_documents set path='%.pdf' where path like '%.docx';

```

**Comment by BalammaBoya** [comment]
![Screenshot from 2019-03-15 11-14-08](https://user-images.githubusercontent.com/22425444/54414009-b357a500-471d-11e9-9378-1c74748d8596.png)
