### ISSUE TITLE
Restrict size of each file to 2 MB while uploading files into outreach portal.

### ISSUE THREAD

**Issue by madhavipuliraju** [vlead/outreach-portal#330]
Restrict size of each file to 2 MB while uploading files into outreach portal.

**Comment by madhavipuliraju** [comment]
Reference: http://flask.pocoo.org/docs/1.0/patterns/fileuploads/

**Comment by BalammaBoya** [comment]
![Screenshot from 2019-03-15 11-12-03](https://user-images.githubusercontent.com/22425444/54413975-9ae78a80-471d-11e9-97d0-0c8b54005252.png)
