### ISSUE TITLE
Unable to update the status from Inactive to Active in Manage Nodal centers tab

### ISSUE THREAD

**Issue by mrudhvika940** [vlead/outreach-portal#341]
In **Manage Nodal Centers** tab, while trying to update the status of "TASK Hyderabad" from Inactive to Active " Invalid username" error is displayed. Please find the attached screen shot.

![screenshot from 2019-01-23 16-21-26](https://user-images.githubusercontent.com/15810190/51601652-fa4dc900-1f2a-11e9-8a38-10e77a9a53c2.png)

**Comment by BalammaBoya** [comment]
Resolved.
