### ISSUE TITLE
Unable to add Nodal center

### ISSUE THREAD

**Issue by mrudhvika940** [vlead/outreach-portal#342]
While creating a new nodal center in "Manage Nodal Center" tab, it displays "Invalid User name" error. Please find the screen shot.

![screenshot from 2019-01-23 16-52-14](https://user-images.githubusercontent.com/15810190/51603310-819d3b80-1f2f-11e9-9161-4a3b37553206.png)

**Comment by BalammaBoya** [comment]
Resolved.
