### ISSUE TITLE
Active /Inactive data count has to be reflected on home page

### ISSUE THREAD

**Issue by mrudhvika940** [vlead/outreach-portal#343]
The Active/Inactive data count of Nodal centers and Nodal Coordinators has to be reflected on home page

**Comment by madhavipuliraju** [comment]
Nodal centers are reflecting based on "**Active**" status. We do not have Nodal Coordinators count on home page.

**Comment by madhavipuliraju** [comment]
![screenshot from 2019-02-12 15-07-55](https://user-images.githubusercontent.com/7077897/52626037-58415100-2ed8-11e9-9cac-d1e6c407c0d3.png)
