### ISSUE TITLE
Nodal Coordinators default status has to be Active

### ISSUE THREAD

**Issue by mrudhvika940** [vlead/outreach-portal#344]
Default status for add Nodal Coordinator is empty. It has to be Active when we create a new Nodal Coordinator. Please find the attached screen shot.

![screenshot from 2019-01-24 09-44-45](https://user-images.githubusercontent.com/15810190/51654236-e0f55d00-1fbc-11e9-8fe2-14fc503f005c.png)

**Comment by BalammaBoya** [comment]
Resolved.

**Comment by madhavipuliraju** [comment]
![screenshot from 2019-02-12 15-04-05](https://user-images.githubusercontent.com/7077897/52625663-7e1a2600-2ed7-11e9-8df5-fb6d0d8a08e3.png)
