### ISSUE TITLE
Fix google map loading issue on outreach portal home page. 

### ISSUE THREAD

**Issue by BalammaBoya** [vlead/outreach-portal#353]
Fix google map loading issue on outreach portal home page.

**Comment by BalammaBoya** [comment]
Resolved.

**Comment by madhavipuliraju** [comment]
![screenshot from 2019-02-12 14-55-17](https://user-images.githubusercontent.com/7077897/52625099-45c61800-2ed6-11e9-8fba-1853b10f6f26.png)
