### ISSUE TITLE
Displaying Active Nodal center in nodal centers page before login

### ISSUE THREAD

**Issue by mrudhvika940** [vlead/outreach-portal#389]
After marking the the nodal centers with the active/inactive status, only active colleges should be displayed in the nodal centers page. Please look into the attached screenshot. 

Description wrto screenshots
Although we made Abhinav hitech is inactive, it is displaying list of nodal centers.

![outreach1](https://user-images.githubusercontent.com/15810190/54660516-c17e3a80-4afc-11e9-8b45-4e8326498a4f.jpg)
![outreach2](https://user-images.githubusercontent.com/15810190/54660518-c216d100-4afc-11e9-9a6f-03c01f51e848.jpg)

**Comment by madhavipuliraju** [comment]
Added Filter to Center Status column to filter Active and Inactive Centers as shown in the screenshot.
![Screenshot from 2019-03-31 20-27-44](https://user-images.githubusercontent.com/7077897/55290675-bb893300-53f3-11e9-9e28-a179d95743f7.png)

**Comment by madhavipuliraju** [comment]
![Screenshot from 2019-03-31 20-30-18](https://user-images.githubusercontent.com/7077897/55290681-d196f380-53f3-11e9-8544-b53cafa55f8b.png)

**Comment by mrudhvika940** [comment]
Unable to sort active status. Typing active in the search bar displaying both active/inactive status.
But the requirement is we need to display only active colleges. Inactive colleges should not be displayed.

**Comment by madhavipuliraju** [comment]
Requirement is to display all nodal centres (irrespective of the status). But on the analytics page, Total nodal centres number will have only active centres. This issue was confirmed with lalit as well.

**Comment by madhavipuliraju** [comment]
![Screenshot from 2019-04-29 11-47-32](https://user-images.githubusercontent.com/7077897/56879042-99c3b000-6a74-11e9-98ac-03983bfd0591.png)
