### ISSUE TITLE
Unable to login in the test environment

### ISSUE THREAD

**Issue by mrudhvika940** [vlead/outreach-portal#411]
Unable to login in test environment

URL :  http://test-outreach.vlabs.ac.in

![Screenshot from 2019-04-24 10-26-54](https://user-images.githubusercontent.com/15810190/56633521-2557ce00-667c-11e9-96dd-748c53774f84.png)

**Comment by madhavipuliraju** [comment]
UnAuthorized error means that email is not registered/unavailable in the database. Hence showing this error. Please use the correct credentials to login.
