### ISSUE TITLE
Display Box size of the data has to be increased

### ISSUE THREAD

**Issue by mrudhvika940** [vlead/outreach-portal#412]
Displaying the data box size has to be increase as the view is small and hard to access data.

![Screenshot from 2019-04-24 12-56-59](https://user-images.githubusercontent.com/15810190/56640378-7d98cb00-6690-11e9-9c71-557ab2bfb308.png)

**Comment by madhavipuliraju** [comment]
![Screenshot from 2019-04-26 12-05-50](https://user-images.githubusercontent.com/7077897/56787939-aa2d1e00-681b-11e9-8da0-4a237a0eb5ef.png)
