### ISSUE TITLE
Unable to upload reports as edit reports button is not visible

### ISSUE THREAD

**Issue by mrudhvika940** [vlead/outreach-portal#429]
Edit reports button is not visible in the pending action workshops page to upload the documents.

Attached the screen shot of the issue.

![Screenshot from 2019-04-30 11-11-13](https://user-images.githubusercontent.com/15810190/56942541-f8eaf880-6b38-11e9-97d1-1b8e2624ab84.png)

**Comment by madhavipuliraju** [comment]
![Screenshot from 2019-04-30 11-31-00](https://user-images.githubusercontent.com/7077897/56943087-87607980-6b3b-11e9-9c2c-422b4ab7d3f6.png)
