### ISSUE TITLE
Missing Virtual Labs WorkshopFAQ link in footer

### ISSUE THREAD

**Issue by BalammaBoya** [vlead/outreach-portal#436]
![Screenshot from 2019-06-03 15-43-13](https://user-images.githubusercontent.com/22425444/58794814-b7a5a700-8616-11e9-803b-e3ed995a586d.png)
There are two types of FAQs: 1. Virtual Labs and 2. Virutal Labs Workshop 
In the footer we are serving only Virtual Labs FAQ link. Missing Virtual Labs Workshop FAQ
![Screenshot from 2019-06-03 15-43-06](https://user-images.githubusercontent.com/22425444/58794852-cee49480-8616-11e9-8677-5cc8f50110cc.png)

**Comment by madhavipuliraju** [comment]
Fixed.
![Screenshot from 2019-06-07 11-46-13](https://user-images.githubusercontent.com/7077897/59084714-e32bd880-8919-11e9-9d18-7a44b74d0ccc.png)

**Comment by madhavipuliraju** [comment]
![Screenshot from 2019-10-17 12-25-46](https://user-images.githubusercontent.com/7077897/66984914-4eac6080-f0d9-11e9-9a3e-66d90f8d96ee.png)
