### ISSUE TITLE
email address can be clickable in the footer

### ISSUE THREAD

**Issue by BalammaBoya** [vlead/outreach-portal#438]
email address can be clickable in the footer

![Screenshot from 2019-06-03 15-55-34](https://user-images.githubusercontent.com/22425444/58795348-0c95ed00-8618-11e9-86c5-894f4f6a1382.png)

**Comment by madhavipuliraju** [comment]
Fixed.
![Screenshot from 2019-06-07 11-54-31](https://user-images.githubusercontent.com/7077897/59085076-0acf7080-891b-11e9-9643-d6e332520455.png)
