### ISSUE TITLE
Nodal centers-list is not loading 

### ISSUE THREAD

**Issue by BalammaBoya** [vlead/outreach-portal#439]
Nodal centers-list list is not loading (when ever user clicks from home page) 

![Screenshot from 2019-06-03 15-57-54](https://user-images.githubusercontent.com/22425444/58795561-9e9df580-8618-11e9-8d8c-94d6204b332c.png)

**Comment by madhavipuliraju** [comment]
![Screenshot from 2019-07-01 12-00-24](https://user-images.githubusercontent.com/7077897/60415100-d5573380-9bf7-11e9-8497-6d9a86b58122.png)
