### ISSUE TITLE
Links in Reference documents (login through IoC & Nodal Coordinator) is not working 

### ISSUE THREAD

**Issue by mrudhvika940** [vlead/outreach-portal#441]
Links for **Reference_Attendance Sheet for Students.pdf** and **Reference_Attendance Sheet for Faculty.pdf** are broken when login through **IoC & Nodal Coordinator**. Please find the attached screen shots.

![Screenshot (3)](https://user-images.githubusercontent.com/15810190/58806088-08c39400-8633-11e9-9e0a-a526d875cc6d.png)
![Screenshot (2)](https://user-images.githubusercontent.com/15810190/58806089-095c2a80-8633-11e9-9e4c-542a5ab2dae1.png)

**Comment by madhavipuliraju** [comment]
We haven't copied documents to the uploads folder in server. Hence the error.
