### ISSUE TITLE
view option is not working in the manage documents page 

### ISSUE THREAD

**Issue by BalammaBoya** [vlead/outreach-portal#443]
View button/option is not working in the manage documents page with admin logins. 

![Screenshot from 2019-06-04 16-30-50](https://user-images.githubusercontent.com/22425444/58874451-74b30480-86e6-11e9-99fb-991c7bff6d62.png)

**Comment by madhavipuliraju** [comment]
Uploads folder does not have files. Hence the error. This will be resolved once we copy all the files.
