### ISSUE TITLE
unable to add document using add document button in the manage document page

### ISSUE THREAD

**Issue by BalammaBoya** [vlead/outreach-portal#445]
unable to add document using add document button in the manage document page using admin logins. 
![Screenshot from 2019-06-04 16-40-53](https://user-images.githubusercontent.com/22425444/58874889-a8daf500-86e7-11e9-9258-1788b42d2ff0.png)

![Screenshot from 2019-06-04 16-42-06](https://user-images.githubusercontent.com/22425444/58874909-b55f4d80-86e7-11e9-9a9d-1e04ebf3ee77.png)

**Comment by madhavipuliraju** [comment]
![Screenshot from 2019-06-06 13-13-24](https://user-images.githubusercontent.com/7077897/59015721-4441a680-885d-11e9-804e-81d5e6130435.png)
