### ISSUE TITLE
can add back button in the workshop page for easy navigation

### ISSUE THREAD

**Issue by BalammaBoya** [vlead/outreach-portal#446]
can add back button in the workshop page using oc logins

![Screenshot from 2019-06-04 20-53-06](https://user-images.githubusercontent.com/22425444/58891893-f026ad00-870a-11e9-90ec-7122c2a376d8.png)

**Comment by madhavipuliraju** [comment]
![Screenshot from 2019-06-26 14-40-17](https://user-images.githubusercontent.com/7077897/60167251-5ab99d00-9820-11e9-867f-49496e506dbc.png)
