### ISSUE TITLE
unable to view the page using button in the workshop, usage, participants pages

### ISSUE THREAD

**Issue by BalammaBoya** [vlead/outreach-portal#447]
unable to view the page using button in the workshop, usage, participants pages using ioc logins

![Screenshot from 2019-06-04 21-09-09](https://user-images.githubusercontent.com/22425444/58893246-5e6c6f00-870d-11e9-9e7d-fd1ced8ec26a.png)

**Comment by madhavipuliraju** [comment]
Uploads folder does not have files. Hence the error. This will be resolved once we copy all the files.
