### ISSUE TITLE
submit button is inactive in the workshop, usage and participants edit pages

### ISSUE THREAD

**Issue by BalammaBoya** [vlead/outreach-portal#448]
submit button is inactive in the workshop, usage and participants edit pages using nc logins: 

![Screenshot from 2019-06-04 21-21-11](https://user-images.githubusercontent.com/22425444/58894079-f585f680-870e-11e9-9df5-6d9e25bf6303.png)

**Comment by madhavipuliraju** [comment]
Need to edit 'Gateway IP Address' value. If you don't want to edit this value, then remove the none value then submit button will automatically enable.
