### ISSUE TITLE
can add back button in the workshop, usage and participants edit pages

### ISSUE THREAD

**Issue by BalammaBoya** [vlead/outreach-portal#449]
can add back button in the workshop, usage and participants edit pages because if user click on edit icon, the page redirecting to edit workshop page, so if we add back button it's easy to navigate. 

![Screenshot from 2019-06-04 21-25-15](https://user-images.githubusercontent.com/22425444/58894253-439afa00-870f-11e9-8d9c-8e2744ca4626.png)

**Comment by madhavipuliraju** [comment]
Added back link
![Screenshot from 2019-06-20 14-44-35](https://user-images.githubusercontent.com/7077897/59836902-facb7e00-9369-11e9-8208-fb3543f4c997.png)

**Comment by madhavipuliraju** [comment]
Added back link
![Screenshot from 2019-06-20 14-44-35](https://user-images.githubusercontent.com/7077897/59836902-facb7e00-9369-11e9-8208-fb3543f4c997.png)

**Comment by madhavipuliraju** [comment]
Added back link

![Screenshot from 2019-06-20 14-44-35](https://user-images.githubusercontent.com/7077897/59836902-facb7e00-9369-11e9-8208-fb3543f4c997.png)

**Comment by madhavipuliraju** [comment]
![Screenshot from 2019-06-26 14-46-34](https://user-images.githubusercontent.com/7077897/60167701-3c07d600-9821-11e9-88f1-33db45ff9a17.png)

**Comment by madhavipuliraju** [comment]
![Screenshot from 2019-06-26 14-52-38](https://user-images.githubusercontent.com/7077897/60168226-129b7a00-9822-11e9-9e4c-2f7b30bfd5bd.png)
