### ISSUE TITLE
QA_OC_Logo

### ISSUE THREAD

**Issue by kolliSuman** [vlead/outreach-portal#58]
Defect Description:
When we click on the 'virtual labs' logo from the other header pages,it is displaying the same page instead it should redirect to the landing page(or)dashboard of the portal
eg:When we click on the 'virtual labs' logo from the reference documents page,it is redirecting to the My profile page only.

Actual Result:
When we click on the 'virtual labs' logo from the other header pages(Dashboard,Manage Outreach Coordinator,Manage nodel center,Manage workshop and reference documents,it is displaying the same page

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM , 
Processor:i5,

Test Step Link:
https://github.com/vlead/outreach-portal/blob/master/test-cases/integration_test-cases/OC/OC_92_logo_p2.org

Attachment :
![oc](https://cloud.githubusercontent.com/assets/14869397/12050066/9d2fc968-af15-11e5-9579-f20b51c84934.png)

**Comment by dinnu93** [comment]
https://github.com/vlead/outreach-portal/commit/b240e606711b3378f598a5f8b975468bfaa2f143

**Comment by dinnu93** [comment]
Fixed in above commit
