### ISSUE TITLE
QA_OC_Refresh

### ISSUE THREAD

**Issue by kolliSuman** [vlead/outreach-portal#63]
Defect Description:
In the OC section when we refresh a page apart from the dashboard page it is redirecting to the dashboard page instead it should redirect to the Same page only 
Eg:When we click on the refresh button from the Manage Workshops page it is redirecting to the dashboard page instead it should redirect to the Manage Workshops page only  .

Actual Result:
In the OC section when we refresh a page apart from the dashboard page it is redirecting to the dashboard page 
Eg:When we click on the refresh button from the Manage Workshops page it is redirecting to the dashboard page.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5,

Test Step Link:
https://github.com/vlead/outreach-portal/blob/master/test-cases/integration_test-cases/OC/OC_93_refresh_p2.org

Attachment :
![oc](https://cloud.githubusercontent.com/assets/14869397/12084104/b8228824-b2d4-11e5-9fe7-d505a91430fe.png)

**Comment by ksripathi** [comment]
Hello QA team,

As this outreach portal is an Angular front end application each and every section will refresh automatically when page loads. And by default the angular router is set to dashboard hence no need to be in current state
