### ISSUE TITLE
QA_Admin_Refresh

### ISSUE THREAD

**Issue by kolliSuman** [vlead/outreach-portal#64]
Defect Description:
In the admin section when we refresh the page apart from the dashboard page it is redirecting to the dashboard page instead it should redirect to the Same page only 
Eg:When we click on the refresh button from the My Profile page it is redirecting to the dashboard page instead it should redirect to the My Profile page only.

Actual Result:
In the admin section when we refresh the page apart from the dashboard page it is redirecting to the dashboard page
Eg:When we click on the refresh button from the My Profile page it is redirecting to the dashboard page
Eg:When we click on the refresh button from the Manage Workshops page it is redirecting to the dashboard page.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5,

Test Step Link:
https://github.com/vlead/outreach-portal/blob/master/test-cases/integration_test-cases/Admin/Admin_70_refresh_p2.org

Attachment :
![admin](https://cloud.githubusercontent.com/assets/14869397/12084143/6016469c-b2d5-11e5-99f7-0267ed00c8bb.png)

**Comment by ksripathi** [comment]
Hello QA team,

As this outreach portal is an Angular front end application each and every section will refresh automatically  when page loads. And by default the angular router is set to dashboard hence no need to be in current state
