### ISSUE TITLE
QA_Admin_view doc

### ISSUE THREAD

**Issue by kolliSuman** [vlead/outreach-portal#69]
Defect Description:
In the document details page of Manage documents, when we upload an gif format file and if we click on the click here button displayed under the view column it is opening a new tab and redirecting to the dashboard page instead the it should open a new tab and display the uploaded file on the screen .

Actual Result:
In the document details page of Manage documents, when we upload an gif format file and if we click on the click here button displayed under the view column it is opening a new tab and redirecting to the dashboard page.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5,

Test Step Link:
https://github.com/vlead/outreach-portal/blob/master/test-cases/integration_test-cases/Admin/Admin_37_view%20doc_p1.org

Attachment :
![view](https://cloud.githubusercontent.com/assets/14869397/12201299/80142e92-b649-11e5-83b3-852abac88a45.png)

**Comment by dinnu93** [comment]
That's because the file was not uploaded it works now.
