### ISSUE TITLE
QA_Admin_view doc

### ISSUE THREAD

**Issue by kolliSuman** [vlead/outreach-portal#70]
Defect Description:
In the document details page of Manage documents, when we upload an csv format file and if we click on the click here button displayed under the view column a download pop-up box is displayed on the screen instead the it should open a new tab and display the uploaded file on the screen  .

Actual Result:
In the document details page of Manage documents, when we upload an csv format file and if we click on the click here button displayed under the view column a download pop-up box is displayed on the screen.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5,

Test Step Link:
https://github.com/vlead/outreach-portal/blob/master/test-cases/integration_test-cases/Admin/Admin_37_view%20doc_p1.org

Attachment : 
![csv](https://cloud.githubusercontent.com/assets/14869397/12201341/db12bb92-b649-11e5-9ecc-4c709cf81fe6.png)

**Comment by dinnu93** [comment]
View file will be the way that the browser handles a file format, The function of view button is to allow users to view or download the files.
