### ISSUE TITLE
QA_Admin_Edit doc

### ISSUE THREAD

**Issue by kolliSuman** [vlead/outreach-portal#9]
Defect Description:
There is no edit button present in the document details page.instead a edit button should be presnt inorder to update details of that documents.

Actual Result:
There is no edit button present in the document details page.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Test Step Link:
https://github.com/vlead/outreach-portal/blob/master/test-cases/integration_test-cases/Admin/Admin_48_edit%20doc_p1.org

Attachment : 
![7](https://cloud.githubusercontent.com/assets/14869397/12017859/f33a90ee-ad81-11e5-9209-59463e917fdf.png)

**Comment by dinnu93** [comment]
Not required .
